name: taskati
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  image_picker: ^1.2.1
  lottie: ^3.3.2
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  date_picker_timeline: ^1.2.7
  # easy_date_timeline: ^2.0.9

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 600
